### ISSUE TITLE
When reloaded, code style is not applied (on Firefox)

### ISSUE THREAD

**Issue by Toub** [slara/generator-reveal#71] opened 2015-09-07 08:16 UTC
When the page is reloaded, the code style is not always applied on Firefox.

It looks like the browser is still loading something (but I can't figure what).

No problem with Chrome.

**Comment by janraasch** [comment] 2015-09-07 12:17
Hi @Toub, have you looked at the respective issues on the https://github.com/gruntjs/grunt-contrib-watch/ repo?

If that does not help, can you provide a concrete example project? And some steps to reproduce the issue?

**Comment by Toub** [comment] 2015-09-12 09:22
Hi @janraasch 

I just reproduced the problem with the last version of the generator.

Steps to reproduce:

* generate a new reveal app with default options 
* run "grunt serve"
* replace index.md with index.html with the following content (and update list.json):

    <section>
        <pre><code data-trim>
    (def lazy-fib
      (concat
       [0 1]
       ((fn rfib [a b]
            (lazy-cons (+ a b) (rfib b (+ a b)))) 0 1)))
        </code></pre>
    </section>

* in firefox, the text is highlighted
* update your html (e.g. append "<p>test</p>")
* firefox is loading something (but I can't figure what)
* the text is not highlighted

Here is the console output:

    Done, without errors.
    Completed in 0.900s at Sat Sep 12 2015 10:09:21 GMT+0100 (WEST) - Waiting...
    >> File "index.html" changed.
    Completed in 0.000s at Sat Sep 12 2015 10:09:21 GMT+0100 (WEST) - Waiting...
    >> File "slides/index.html" changed.
    Completed in 0.000s at Sat Sep 12 2015 10:09:32 GMT+0100 (WEST) - Waiting...

If I refresh the page, it is ok. (but I had more complex application when refreshing was not enough)

It is not 100% reproducible, it depends of the modifications (but there is no exact scenario)...

Probably related to grunt-contrib-watch, as there are many bugs and poor maintenance now.

**Comment by janraasch** [comment] 2015-09-12 12:53
Ok. I was able to reproduce this as well.

This seems to be a general problem with the way external files are loaded in `reveal.js` with `livereload` on FireFox. The simplest workaround seems to be: 

Add `async: true` to the `markdown` dependency in `templates/_index.html` (line 76):

```js
{ src: 'bower_components/reveal.js/plugin/markdown/markdown.js', async: true, condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
```

This problem exists even on the [reveal.js](https://github.com/hakimel/reveal.js) repo using their `grunt serve` task with live reloading enabled in FireFox when one adds a

```html
<section data-markdown="CONTRIBUTING.md"></section>
```

to their `index.html`. FireFox just keeps *loading* never firing the load event which would then trigger highlighting to work.

I hope that helps. I will close the issue here, since this is either a reveal.js, livereload-js or maybe even a FireFox bug. If you want to pursue this further I would suggest opening an issue on the reveal.js repo.

**Closed by janraasch** 2015-09-12 12:53 UTC
